-- 000005_muscles_custom.up.sql
-- Second muscle backfill wave: user-added custom exercises (ATG/KOT-style
-- movements, kettlebell work, mobility and stretching) that the canonical
-- FitNotes-name map in 000004 could not match. Same rules: normalized-name
-- match, only empty fields are filled, last_modified is bumped so clients
-- pull the enriched rows, and re-running is a no-op once fields are set.

WITH muscle_map(name_norm, prim, sec) AS (
  VALUES
    ('2positionwallstretch', 'Chest, Front Delts', ''),
    ('2wayshoulderfly', 'Side Delts, Rear Delts', 'Traps'),
    ('atgfullrompushups', 'Chest', 'Front Delts, Triceps'),
    ('atgpushup', 'Chest', 'Front Delts, Triceps'),
    ('atgrow', 'Lats, Upper Back', 'Biceps, Rear Delts'),
    ('atgsplitsquat', 'Quads, Glutes', 'Hamstrings, Hip Flexors, Adductors'),
    ('atgsplitsquatprogression', 'Quads, Glutes', 'Hamstrings, Hip Flexors, Adductors'),
    ('atgsplitsquatstretch', 'Hip Flexors, Quads', ''),
    ('altdeadbug', 'Abs', 'Obliques, Hip Flexors'),
    ('altmilitarypress', 'Front Delts, Side Delts', 'Triceps, Traps'),
    ('alternatingsideplankreachthrough', 'Obliques', 'Abs, Side Delts'),
    ('aroundtheworldlegraise', 'Abs, Hip Flexors', 'Obliques'),
    ('assistedpullup', 'Lats', 'Biceps, Upper Back'),
    ('backextensionprogression', 'Lower Back', 'Glutes, Hamstrings'),
    ('backsquat', 'Quads, Glutes', 'Hamstrings, Adductors, Lower Back, Abs'),
    ('backextension', 'Lower Back', 'Glutes, Hamstrings'),
    ('backwardssled', 'Quads', 'Calves, Glutes'),
    ('backwardswalking', 'Quads', 'Calves'),
    ('ballstothewall', 'Calves', ''),
    ('bandrotation', 'Obliques', 'Abs'),
    ('bandpullapart', 'Rear Delts, Upper Back', 'Traps'),
    ('bearclaw', 'Forearms', ''),
    ('bentrowwithband', 'Lats, Upper Back', 'Biceps, Rear Delts'),
    ('bentlegcalfraise', 'Calves', ''),
    ('bicepwallstretch', 'Biceps', ''),
    ('blastoffpushup', 'Chest', 'Front Delts, Triceps, Abs'),
    ('bowtoboat', 'Abs', 'Lower Back'),
    ('boxsquat', 'Quads, Glutes', 'Hamstrings, Lower Back'),
    ('bridgehamstringcurl', 'Hamstrings', 'Glutes'),
    ('butterflystretch', 'Adductors', ''),
    ('calfstretchslantboard', 'Calves', ''),
    ('catcow', 'Lower Back', 'Abs'),
    ('chestpress', 'Chest', 'Front Delts, Triceps'),
    ('childpose', 'Lower Back', 'Lats'),
    ('clockswithband', 'Front Delts, Side Delts', 'Rear Delts'),
    ('cobrastretch', 'Abs', 'Hip Flexors'),
    ('copenhagencrunch', 'Adductors, Obliques', 'Abs'),
    ('cossacksquat', 'Quads, Adductors', 'Glutes, Hamstrings'),
    ('couchstretch', 'Hip Flexors, Quads', ''),
    ('dbquadrupedrow', 'Lats, Upper Back', 'Biceps, Abs'),
    ('dbrussiantwist', 'Obliques', 'Abs'),
    ('deadhang', 'Forearms', 'Lats'),
    ('deficitreverselunge', 'Quads, Glutes', 'Hamstrings, Adductors'),
    ('dislocatorswithband', 'Front Delts, Rear Delts', 'Chest'),
    ('doublecrunch', 'Abs', 'Hip Flexors'),
    ('dumbbellplankslide', 'Abs', 'Obliques, Front Delts'),
    ('dumbbellsinglearmbenchrow', 'Lats, Upper Back', 'Biceps, Rear Delts'),
    ('eccentriccablerotations', 'Rear Delts', 'Upper Back'),
    ('eccentricgobletsquat', 'Quads, Glutes', 'Hamstrings, Abs'),
    ('eccentricpullup', 'Lats', 'Biceps, Upper Back, Forearms'),
    ('eccentricpushup', 'Chest', 'Front Delts, Triceps'),
    ('elephantwalk', 'Hamstrings', 'Lower Back'),
    ('externalrotation', 'Rear Delts', 'Upper Back'),
    ('farmerscarry', 'Forearms, Traps', 'Abs, Obliques'),
    ('fingerextensions', 'Forearms', ''),
    ('forearmsoptional', 'Forearms', ''),
    ('frontrackreverselunge', 'Quads, Glutes', 'Hamstrings, Abs, Upper Back'),
    ('fullpullup', 'Lats', 'Biceps, Upper Back, Forearms'),
    ('fullrangeoverheadpress', 'Front Delts, Side Delts', 'Triceps, Traps'),
    ('fullsinglelegcalfraise', 'Calves', ''),
    ('fullsquatprogression', 'Quads, Glutes', 'Hamstrings, Adductors'),
    ('fullhandraise', 'Forearms', ''),
    ('getupsitup', 'Abs', 'Hip Flexors'),
    ('glutebridgereach', 'Glutes', 'Hamstrings, Abs'),
    ('gorillarow', 'Lats, Upper Back', 'Biceps, Lower Back'),
    ('gorillasquat', 'Quads, Glutes', 'Hamstrings, Lower Back'),
    ('groinstretch', 'Adductors', ''),
    ('halfgetupwithband', 'Abs, Obliques', 'Front Delts'),
    ('halfkneelinghipstretch', 'Hip Flexors', ''),
    ('halfkneelingtricepleans', 'Triceps', ''),
    ('halfkneelingvertrow', 'Lats, Upper Back', 'Biceps'),
    ('halfkneelingwindmillwithpress', 'Obliques, Front Delts', 'Abs, Side Delts'),
    ('halfturkishgetupwithdoublepress', 'Abs, Front Delts', 'Obliques, Triceps'),
    ('hamroller', 'Hamstrings', ''),
    ('hamstringbridge', 'Hamstrings', 'Glutes'),
    ('hamstringstretch', 'Hamstrings', ''),
    ('handgrippers', 'Forearms', ''),
    ('handspreads', 'Forearms', ''),
    ('hangingkneeraise', 'Abs, Hip Flexors', 'Obliques, Forearms'),
    ('hangingscapretraction', 'Traps, Upper Back', 'Lats'),
    ('heelofhandraise', 'Forearms', ''),
    ('heeltaps', 'Obliques', 'Abs'),
    ('hindupushup', 'Chest, Front Delts', 'Triceps, Abs'),
    ('hipairplanes', 'Glutes', 'Abductors, Lower Back'),
    ('hipflexors', 'Hip Flexors', ''),
    ('hollowhold', 'Abs', 'Hip Flexors'),
    ('iliacusraise', 'Hip Flexors', ''),
    ('inchwormpushup', 'Chest, Abs', 'Front Delts, Hamstrings'),
    ('internalexternalhiprotation', 'Abductors, Adductors', 'Glutes'),
    ('jeffersoncurl', 'Lower Back, Hamstrings', ''),
    ('jumplungeswitch', 'Quads, Glutes', 'Hamstrings, Calves'),
    ('kbanchoredlegraises', 'Abs, Hip Flexors', ''),
    ('kbarmbar', 'Rear Delts, Obliques', 'Abs'),
    ('kbswing', 'Glutes, Hamstrings', 'Lower Back, Abs'),
    ('lsit', 'Abs, Hip Flexors', 'Triceps'),
    ('lateralhop', 'Calves, Quads', 'Glutes, Abductors'),
    ('lawnmower', 'Lats, Upper Back', 'Biceps, Obliques'),
    ('legraisetopulseup', 'Abs, Hip Flexors', ''),
    ('medballslam', 'Abs, Lats', 'Front Delts, Triceps'),
    ('midspineprogression', 'Upper Back', 'Lower Back'),
    ('mixedrackstepup', 'Quads, Glutes', 'Hamstrings'),
    ('monkeybar', 'Lats, Forearms', 'Biceps'),
    ('narrowtowidepushup', 'Chest, Triceps', 'Front Delts'),
    ('nordic', 'Hamstrings', 'Calves'),
    ('oppositetoetouch', 'Abs, Obliques', 'Hamstrings'),
    ('outerglutestretch', 'Glutes, Abductors', ''),
    ('overcomingisometricsplitsquat', 'Quads, Glutes', 'Hamstrings'),
    ('pallofpress', 'Obliques, Abs', 'Front Delts'),
    ('pancake', 'Adductors, Hamstrings', 'Lower Back'),
    ('pancakepulse', 'Adductors, Hamstrings', 'Lower Back'),
    ('patrickstepup', 'Quads', 'Glutes'),
    ('phaelontwist', 'Obliques', 'Lower Back'),
    ('pigeonstretch', 'Glutes, Abductors', 'Hip Flexors'),
    ('pigeonpushup', 'Glutes, Abductors', ''),
    ('plankkneetaps', 'Abs', 'Obliques'),
    ('plankrolls', 'Abs, Obliques', ''),
    ('plankshouldertaps', 'Abs', 'Obliques, Front Delts'),
    ('plankwalk', 'Abs', 'Front Delts, Obliques'),
    ('plyopushup', 'Chest', 'Triceps, Front Delts'),
    ('plyostepup', 'Quads, Glutes', 'Calves'),
    ('poliquinstepup', 'Quads', 'Glutes'),
    ('powellraise', 'Rear Delts', 'Upper Back'),
    ('pronereach', 'Upper Back, Rear Delts', 'Lower Back'),
    ('psoasleglift', 'Hip Flexors', 'Abs'),
    ('pullover', 'Lats, Chest', 'Triceps'),
    ('pushupplankslide', 'Chest, Abs', 'Front Delts, Triceps'),
    ('pushuptorotation', 'Chest, Obliques', 'Front Delts, Triceps'),
    ('pushuptoshouldertap', 'Chest, Abs', 'Front Delts, Triceps'),
    ('pushups', 'Chest', 'Front Delts, Triceps'),
    ('qlextension', 'Lower Back, Obliques', ''),
    ('radialulnardeviation', 'Forearms', ''),
    ('rearfootelevateddbromaniandeadlift', 'Hamstrings, Glutes', 'Lower Back'),
    ('reverselunge', 'Quads, Glutes', 'Hamstrings, Adductors'),
    ('reverselungetopresswithband', 'Quads, Glutes, Front Delts', 'Hamstrings, Triceps'),
    ('rollerangels', 'Upper Back, Rear Delts', 'Chest'),
    ('runnerslungejumps', 'Quads, Glutes', 'Hamstrings, Calves'),
    ('scissorstep', 'Hip Flexors, Quads', 'Abs'),
    ('seatedqlstretch', 'Lower Back, Obliques', ''),
    ('seatedgoodmorning', 'Hamstrings, Lower Back', 'Glutes'),
    ('shoulderexternalrotation', 'Rear Delts', 'Upper Back'),
    ('shoulderpress', 'Front Delts, Side Delts', 'Triceps, Traps'),
    ('sideplankdips', 'Obliques', 'Abs'),
    ('sideplankreachthrough', 'Obliques', 'Abs, Side Delts'),
    ('sidesteplunge', 'Quads, Adductors', 'Glutes, Hamstrings'),
    ('singlearmbentrowwithband', 'Lats, Upper Back', 'Biceps, Rear Delts'),
    ('singlearmkboverheadcarry', 'Side Delts, Traps', 'Abs, Obliques'),
    ('singlearmlateralshoulderfly', 'Side Delts', 'Traps'),
    ('singlearmrow', 'Lats, Upper Back', 'Biceps, Rear Delts'),
    ('singleleglateraljump', 'Quads, Calves', 'Glutes, Abductors'),
    ('singlelegplank', 'Abs', 'Glutes, Lower Back'),
    ('singlelegpushup', 'Chest', 'Front Delts, Triceps, Abs'),
    ('singlelegromaniandeadlift', 'Hamstrings, Glutes', 'Lower Back, Abductors'),
    ('spiderpulse', 'Hip Flexors, Adductors', ''),
    ('spinekneepull', 'Lower Back', 'Glutes'),
    ('splitstancealtwidepress', 'Front Delts, Side Delts', 'Triceps, Abs'),
    ('splitstancearnoldpress', 'Front Delts, Side Delts', 'Triceps, Traps'),
    ('splitstancecablerow', 'Lats, Upper Back', 'Biceps, Abs'),
    ('splitstancepresswithband', 'Front Delts, Side Delts', 'Triceps, Abs'),
    ('splitstancepushpress', 'Front Delts, Side Delts', 'Triceps, Quads, Glutes'),
    ('splitstancereciprocaldbpress', 'Front Delts, Side Delts', 'Triceps, Abs'),
    ('splitstancesidedips', 'Obliques', 'Abs'),
    ('splitstancesinglearmpress', 'Front Delts, Side Delts', 'Triceps, Obliques'),
    ('splitstancesinglearmpresswithband', 'Front Delts, Side Delts', 'Triceps, Obliques'),
    ('straightlegcalfraise', 'Calves', ''),
    ('suitcasecarry', 'Obliques, Forearms', 'Traps, Abs'),
    ('superman', 'Lower Back', 'Glutes'),
    ('switchgrippullup', 'Lats', 'Biceps, Upper Back, Forearms'),
    ('tspinerotation', 'Upper Back', 'Obliques'),
    ('trxcheststretch', 'Chest', 'Front Delts'),
    ('tabletopplankslide', 'Abs', 'Front Delts'),
    ('thoracictwist', 'Upper Back', 'Obliques'),
    ('tibialisraiserotation', 'Calves', ''),
    ('tibialisraise', 'Calves', ''),
    ('toereachsitup', 'Abs', 'Hip Flexors'),
    ('trapbardeadlift', 'Glutes, Quads, Hamstrings', 'Lower Back, Traps, Forearms'),
    ('trap3raise', 'Traps, Rear Delts', 'Upper Back'),
    ('triceplean', 'Triceps', ''),
    ('tubewalk', 'Abductors, Glutes', ''),
    ('upoverlegraise', 'Abs, Hip Flexors', 'Obliques'),
    ('upchopwithband', 'Obliques', 'Abs, Front Delts'),
    ('updownwarddog', 'Front Delts, Hamstrings', 'Abs, Calves'),
    ('upwarddog', 'Abs, Hip Flexors', 'Lower Back'),
    ('upwarddogwithtwist', 'Abs, Obliques', 'Hip Flexors'),
    ('vups', 'Abs', 'Hip Flexors'),
    ('vmosquats', 'Quads', 'Glutes'),
    ('vertjump', 'Quads, Glutes', 'Calves, Hamstrings'),
    ('wallsit', 'Quads', 'Glutes'),
    ('warrior3', 'Glutes, Hamstrings', 'Lower Back, Abs'),
    ('widelegreachhold', 'Hamstrings, Adductors', 'Lower Back'),
    ('widepushup', 'Chest', 'Front Delts, Triceps'),
    ('windshieldwipers', 'Obliques, Abs', ''),
    ('wriststretch', 'Forearms', ''),
    ('wristflexionextension', 'Forearms', ''),
    ('wristsupinationpronation', 'Forearms', ''),
    ('xstepwithband', 'Abductors, Glutes', ''),
    ('zeusrowwithband', 'Lats, Upper Back', 'Biceps, Rear Delts'),
    ('zottmancurl', 'Biceps, Forearms', ''),
    ('singlelegforwardreversejump', 'Quads, Calves', 'Glutes, Hamstrings')
)
UPDATE exercises e
SET primary_muscles = CASE
      WHEN e.primary_muscles IS NULL OR e.primary_muscles = '' THEN m.prim
      ELSE e.primary_muscles
    END,
    secondary_muscles = CASE
      WHEN e.secondary_muscles IS NULL OR e.secondary_muscles = '' THEN m.sec
      ELSE e.secondary_muscles
    END,
    last_modified = NOW()
FROM muscle_map m
WHERE lower(regexp_replace(e.name, '[^a-zA-Z0-9]+', '', 'g')) = m.name_norm
  AND (
    ((e.primary_muscles IS NULL OR e.primary_muscles = '') AND m.prim <> '')
    OR ((e.secondary_muscles IS NULL OR e.secondary_muscles = '') AND m.sec <> '')
  );
