import type { Category, Exercise } from '../types';

export const DEFAULT_CATEGORIES: Category[] = [
  {
    "id": "c-1",
    "name": "Shoulders",
    "colour": -7453523,
    "sort_order": 0
  },
  {
    "id": "c-2",
    "name": "Triceps",
    "colour": -14176672,
    "sort_order": 0
  },
  {
    "id": "c-3",
    "name": "Biceps",
    "colour": -812014,
    "sort_order": 0
  },
  {
    "id": "c-4",
    "name": "Chest",
    "colour": -4179669,
    "sort_order": 0
  },
  {
    "id": "c-5",
    "name": "Back",
    "colour": -14057287,
    "sort_order": 0
  },
  {
    "id": "c-6",
    "name": "Legs",
    "colour": -11226442,
    "sort_order": 0
  },
  {
    "id": "c-7",
    "name": "Abs",
    "colour": -13877680,
    "sort_order": 0
  },
  {
    "id": "c-8",
    "name": "Cardio",
    "colour": -8418163,
    "sort_order": 0
  }
];

export const DEFAULT_EXERCISES: Exercise[] = [
  {
    "id": "e-overhead-press",
    "name": "Overhead Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps"
  },
  {
    "id": "e-seated-dumbbell-press",
    "name": "Seated Dumbbell Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps"
  },
  {
    "id": "e-lateral-dumbbell-raise",
    "name": "Lateral Dumbbell Raise",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Side Delts",
    "secondary_muscles": "Traps"
  },
  {
    "id": "e-front-dumbbell-raise",
    "name": "Front Dumbbell Raise",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts",
    "secondary_muscles": "Side Delts, Chest"
  },
  {
    "id": "e-push-press",
    "name": "Push Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps, Quads, Glutes"
  },
  {
    "id": "e-behind-the-neck-barbell-press",
    "name": "Behind The Neck Barbell Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps"
  },
  {
    "id": "e-hammer-strength-shoulder-press",
    "name": "Hammer Strength Shoulder Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps"
  },
  {
    "id": "e-seated-dumbbell-lateral-raise",
    "name": "Seated Dumbbell Lateral Raise",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Side Delts",
    "secondary_muscles": "Traps"
  },
  {
    "id": "e-lateral-machine-raise",
    "name": "Lateral Machine Raise",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Side Delts",
    "secondary_muscles": "Traps"
  },
  {
    "id": "e-rear-delt-dumbbell-raise",
    "name": "Rear Delt Dumbbell Raise",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Rear Delts",
    "secondary_muscles": "Upper Back, Traps"
  },
  {
    "id": "e-rear-delt-machine-fly",
    "name": "Rear Delt Machine Fly",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Rear Delts",
    "secondary_muscles": "Upper Back, Traps"
  },
  {
    "id": "e-arnold-dumbbell-press",
    "name": "Arnold Dumbbell Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps"
  },
  {
    "id": "e-one-arm-standing-dumbbell-press",
    "name": "One-Arm Standing Dumbbell Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps, Obliques"
  },
  {
    "id": "e-cable-face-pull",
    "name": "Cable Face Pull",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Rear Delts, Upper Back",
    "secondary_muscles": "Traps, Biceps"
  },
  {
    "id": "e-log-press",
    "name": "Log Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps, Upper Back"
  },
  {
    "id": "e-smith-machine-overhead-press",
    "name": "Smith Machine Overhead Press",
    "category_id": "c-1",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Front Delts, Side Delts",
    "secondary_muscles": "Triceps, Traps"
  },
  {
    "id": "e-close-grip-barbell-bench-press",
    "name": "Close Grip Barbell Bench Press",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps, Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-v-bar-push-down",
    "name": "V-Bar Push Down",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-parallel-bar-triceps-dip",
    "name": "Parallel Bar Triceps Dip",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps, Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-lying-triceps-extension",
    "name": "Lying Triceps Extension",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-rope-push-down",
    "name": "Rope Push Down",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-cable-overhead-triceps-extension",
    "name": "Cable Overhead Triceps Extension",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-ez-bar-skullcrusher",
    "name": "EZ-Bar Skullcrusher",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-dumbbell-overhead-triceps-extension",
    "name": "Dumbbell Overhead Triceps Extension",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-ring-dip",
    "name": "Ring Dip",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps, Chest",
    "secondary_muscles": "Front Delts, Abs"
  },
  {
    "id": "e-smith-machine-close-grip-bench-press",
    "name": "Smith Machine Close Grip Bench Press",
    "category_id": "c-2",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Triceps, Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-barbell-curl",
    "name": "Barbell Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-ez-bar-curl",
    "name": "EZ-Bar Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-dumbbell-curl",
    "name": "Dumbbell Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-seated-incline-dumbbell-curl",
    "name": "Seated Incline Dumbbell Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-seated-machine-curl",
    "name": "Seated Machine Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-dumbbell-hammer-curl",
    "name": "Dumbbell Hammer Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps, Forearms",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-cable-curl",
    "name": "Cable Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-ez-bar-preacher-curl",
    "name": "EZ-Bar Preacher Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-dumbbell-concentration-curl",
    "name": "Dumbbell Concentration Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-dumbbell-preacher-curl",
    "name": "Dumbbell Preacher Curl",
    "category_id": "c-3",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Biceps",
    "secondary_muscles": "Forearms"
  },
  {
    "id": "e-flat-barbell-bench-press",
    "name": "Flat Barbell Bench Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Front Delts, Triceps"
  },
  {
    "id": "e-flat-dumbbell-bench-press",
    "name": "Flat Dumbbell Bench Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Front Delts, Triceps"
  },
  {
    "id": "e-incline-barbell-bench-press",
    "name": "Incline Barbell Bench Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest, Front Delts",
    "secondary_muscles": "Triceps"
  },
  {
    "id": "e-decline-barbell-bench-press",
    "name": "Decline Barbell Bench Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Triceps, Front Delts"
  },
  {
    "id": "e-incline-dumbbell-bench-press",
    "name": "Incline Dumbbell Bench Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest, Front Delts",
    "secondary_muscles": "Triceps"
  },
  {
    "id": "e-flat-dumbbell-fly",
    "name": "Flat Dumbbell Fly",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-incline-dumbbell-fly",
    "name": "Incline Dumbbell Fly",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-cable-crossover",
    "name": "Cable Crossover",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-incline-hammer-strength-chest-press",
    "name": "Incline Hammer Strength Chest Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest, Front Delts",
    "secondary_muscles": "Triceps"
  },
  {
    "id": "e-decline-hammer-strength-chest-press",
    "name": "Decline Hammer Strength Chest Press",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Triceps, Front Delts"
  },
  {
    "id": "e-seated-machine-fly",
    "name": "Seated Machine Fly",
    "category_id": "c-4",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Chest",
    "secondary_muscles": "Front Delts"
  },
  {
    "id": "e-deadlift",
    "name": "Deadlift",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Glutes, Hamstrings, Lower Back",
    "secondary_muscles": "Quads, Traps, Forearms, Lats"
  },
  {
    "id": "e-pull-up",
    "name": "Pull Up",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats",
    "secondary_muscles": "Biceps, Upper Back, Forearms"
  },
  {
    "id": "e-chin-up",
    "name": "Chin Up",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Biceps",
    "secondary_muscles": "Upper Back, Forearms"
  },
  {
    "id": "e-neutral-chin-up",
    "name": "Neutral Chin Up",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Biceps",
    "secondary_muscles": "Upper Back, Forearms"
  },
  {
    "id": "e-dumbbell-row",
    "name": "Dumbbell Row",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Upper Back",
    "secondary_muscles": "Biceps, Rear Delts, Forearms"
  },
  {
    "id": "e-barbell-row",
    "name": "Barbell Row",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Upper Back",
    "secondary_muscles": "Biceps, Rear Delts, Lower Back, Forearms"
  },
  {
    "id": "e-pendlay-row",
    "name": "Pendlay Row",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Upper Back",
    "secondary_muscles": "Biceps, Rear Delts, Lower Back"
  },
  {
    "id": "e-lat-pulldown",
    "name": "Lat Pulldown",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats",
    "secondary_muscles": "Biceps, Upper Back, Forearms"
  },
  {
    "id": "e-hammer-strength-row",
    "name": "Hammer Strength Row",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Upper Back",
    "secondary_muscles": "Biceps, Rear Delts"
  },
  {
    "id": "e-seated-cable-row",
    "name": "Seated Cable Row",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Upper Back",
    "secondary_muscles": "Biceps, Rear Delts, Forearms"
  },
  {
    "id": "e-t-bar-row",
    "name": "T-Bar Row",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Upper Back",
    "secondary_muscles": "Biceps, Rear Delts, Lower Back"
  },
  {
    "id": "e-barbell-shrug",
    "name": "Barbell Shrug",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Traps",
    "secondary_muscles": "Forearms, Neck"
  },
  {
    "id": "e-machine-shrug",
    "name": "Machine Shrug",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Traps",
    "secondary_muscles": "Forearms, Neck"
  },
  {
    "id": "e-straight-arm-cable-pushdown",
    "name": "Straight-Arm Cable Pushdown",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats",
    "secondary_muscles": "Triceps, Abs"
  },
  {
    "id": "e-rack-pull",
    "name": "Rack Pull",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Glutes, Lower Back",
    "secondary_muscles": "Hamstrings, Traps, Forearms, Lats"
  },
  {
    "id": "e-good-morning",
    "name": "Good Morning",
    "category_id": "c-5",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Hamstrings, Glutes, Lower Back",
    "secondary_muscles": "Abs"
  },
  {
    "id": "e-barbell-squat",
    "name": "Barbell Squat",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Glutes",
    "secondary_muscles": "Hamstrings, Adductors, Lower Back, Abs"
  },
  {
    "id": "e-barbell-front-squat",
    "name": "Barbell Front Squat",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads",
    "secondary_muscles": "Glutes, Adductors, Abs, Upper Back"
  },
  {
    "id": "e-leg-press",
    "name": "Leg Press",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Glutes",
    "secondary_muscles": "Hamstrings, Adductors"
  },
  {
    "id": "e-leg-extension-machine",
    "name": "Leg Extension Machine",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads",
    "secondary_muscles": "Hip Flexors"
  },
  {
    "id": "e-seated-leg-curl-machine",
    "name": "Seated Leg Curl Machine",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Hamstrings",
    "secondary_muscles": "Calves"
  },
  {
    "id": "e-standing-calf-raise-machine",
    "name": "Standing Calf Raise Machine",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Calves",
    "secondary_muscles": ""
  },
  {
    "id": "e-donkey-calf-raise",
    "name": "Donkey Calf Raise",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Calves",
    "secondary_muscles": ""
  },
  {
    "id": "e-barbell-calf-raise",
    "name": "Barbell Calf Raise",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Calves",
    "secondary_muscles": ""
  },
  {
    "id": "e-barbell-glute-bridge",
    "name": "Barbell Glute Bridge",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Glutes",
    "secondary_muscles": "Hamstrings, Quads"
  },
  {
    "id": "e-glute-ham-raise",
    "name": "Glute-Ham Raise",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Hamstrings, Glutes",
    "secondary_muscles": "Lower Back, Calves"
  },
  {
    "id": "e-lying-leg-curl-machine",
    "name": "Lying Leg Curl Machine",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Hamstrings",
    "secondary_muscles": "Calves"
  },
  {
    "id": "e-romanian-deadlift",
    "name": "Romanian Deadlift",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Hamstrings, Glutes",
    "secondary_muscles": "Lower Back, Forearms, Traps"
  },
  {
    "id": "e-stiff-legged-deadlift",
    "name": "Stiff-Legged Deadlift",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Hamstrings, Glutes, Lower Back",
    "secondary_muscles": "Forearms, Traps"
  },
  {
    "id": "e-sumo-deadlift",
    "name": "Sumo Deadlift",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Glutes, Quads, Adductors",
    "secondary_muscles": "Hamstrings, Lower Back, Traps, Forearms"
  },
  {
    "id": "e-seated-calf-raise",
    "name": "Seated Calf Raise",
    "category_id": "c-6",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Calves",
    "secondary_muscles": ""
  },
  {
    "id": "e-ab-wheel-rollout",
    "name": "Ab-Wheel Rollout",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques, Lats, Hip Flexors"
  },
  {
    "id": "e-cable-crunch",
    "name": "Cable Crunch",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques"
  },
  {
    "id": "e-crunch",
    "name": "Crunch",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques"
  },
  {
    "id": "e-crunch-machine",
    "name": "Crunch Machine",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques"
  },
  {
    "id": "e-decline-crunch",
    "name": "Decline Crunch",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques, Hip Flexors"
  },
  {
    "id": "e-dragon-flag",
    "name": "Dragon Flag",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques, Hip Flexors, Lats"
  },
  {
    "id": "e-garhammer",
    "name": "Garhammer",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Hip Flexors, Obliques"
  },
  {
    "id": "e-hanging-leg-raise",
    "name": "Hanging Leg Raise",
    "category_id": "c-7",
    "exercise_type_id": 0,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs, Hip Flexors",
    "secondary_muscles": "Obliques, Forearms"
  },
  {
    "id": "e-plank",
    "name": "Plank",
    "category_id": "c-7",
    "exercise_type_id": 5,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Abs",
    "secondary_muscles": "Obliques, Lower Back"
  },
  {
    "id": "e-side-plank",
    "name": "Side Plank",
    "category_id": "c-7",
    "exercise_type_id": 5,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Obliques",
    "secondary_muscles": "Abs, Abductors"
  },
  {
    "id": "e-cycling",
    "name": "Cycling",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Glutes",
    "secondary_muscles": "Hamstrings, Calves"
  },
  {
    "id": "e-walking",
    "name": "Walking",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Hamstrings, Calves",
    "secondary_muscles": "Glutes, Hip Flexors"
  },
  {
    "id": "e-rowing-machine",
    "name": "Rowing Machine",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Quads",
    "secondary_muscles": "Upper Back, Biceps, Hamstrings, Glutes"
  },
  {
    "id": "e-stationary-bike",
    "name": "Stationary Bike",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Glutes",
    "secondary_muscles": "Hamstrings, Calves"
  },
  {
    "id": "e-swimming",
    "name": "Swimming",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Lats, Chest",
    "secondary_muscles": "Triceps, Front Delts, Upper Back"
  },
  {
    "id": "e-running-treadmill",
    "name": "Running (Treadmill)",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Hamstrings, Calves",
    "secondary_muscles": "Glutes, Hip Flexors"
  },
  {
    "id": "e-running-outdoor",
    "name": "Running (Outdoor)",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Hamstrings, Calves",
    "secondary_muscles": "Glutes, Hip Flexors"
  },
  {
    "id": "e-elliptical-trainer",
    "name": "Elliptical Trainer",
    "category_id": "c-8",
    "exercise_type_id": 3,
    "notes": "",
    "weight_increment": 2.5,
    "default_rest_time": 90,
    "weight_unit_id": 0,
    "is_favourite": false,
    "primary_muscles": "Quads, Glutes",
    "secondary_muscles": "Hamstrings, Calves"
  }
];
