// settings.ts - Default user settings, mirroring the backend schema defaults.
import type { Settings } from '../types';

export const DEFAULT_SETTINGS: Settings = {
  metric: true,
  first_day_of_week: 2, // Monday (FitNotes: 1 Sun, 2 Mon, 7 Sat)
  selected_navigation_item_id: 0,
  weight_increment: 2.5,
  body_weight_increment: 0.1,
  body_weight_goal: false,
  body_weight_goal_weight: null,
  body_weight_show_in_workout_log: true,
  estimated_1rm_max_reps_to_include: 10,
  estimated_1rm_max_apply_to_graph: true,
  track_personal_records: true,
  mark_sets_complete: true,
  auto_select_next_set: true,
  keep_screen_on: false,
  graph_show_points: true,
  graph_show_trend_line: false,
  graph_start_at_zero: false,
  rest_timer_seconds: 90,
  rest_timer_vibrate: true,
  rest_timer_sound: true,
  rest_timer_volume: 100,
  rest_timer_auto_start: false,
  calendar_detail_visible: true,
  calendar_category_dots_visible: true,
  calendar_navigation_bar_visible: true,
  calendar_history_category_dots_visible: true,
  calendar_history_category_names_visible: true,
  calendar_history_sets_visible: true,
  category_sort_order: 0,
  category_show_colours: true,
  measurement_tracker_initial_load: true,
  measurement_show_in_workout_log: true,
  workout_graph_default_graph_type: 0,
  workout_graph_default_time_period: 0,
  analysis_breakdown_breakdown_type: 0,
  analysis_breakdown_time_period: 0,
  exercise_list_detail_type_id: 0,
  workout_timer_auto_start_enabled: false,
  workout_timer_auto_stop_enabled: false,
  home_screen_limit_type_id: 0,
  home_screen_limit_value: 0,
  home_screen_category_visibility_id: 1,
  home_screen_skip_empty_dates: false,
  app_theme_id: 0,
  distance_unit: 1, // km
};
